import { StyleSheet, Platform } from 'react-native';

import { colors, paddings, margins, gaps, fontsize, fontweight } from "../../../../config";

const mobileStyle = StyleSheet.create({
    selectbox:{
        width:"100%",
        padding:paddings.mid,
        borderWidth:1.5,
        borderColor:colors.border_container,
        borderRadius:8,
        backgroundColor:colors.dark_white_container,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
    },
    selected_item_area:{
        flexDirection:"row",
        alignItems:"center",
        columnGap:gaps.mid
    },
    icon:{
        width:30,
        height:20
    },
    text:{
        fontSize:fontsize.mid,
        fontWeight:fontweight.high,
        color:colors.light_black_text
    },
    modal:{
        width:"100%",
        height:"100%"
    },
    container:{
        width:"100%",
        height:"100%",
        paddingVertical:paddings.high,
        borderTopWidth:1,
        borderBottomWidth:1,
        borderColor:colors.border_container
    },
    search_bar:{
        width:"90%",
        marginLeft:"5%",
        padding:paddings.mid,
        paddingVertical:(Platform.OS === "ios") ? paddings.mid : paddings.low,
        borderWidth:1,
        borderColor:colors.border_container,
        borderRadius:4
    },
    flatlist:{
        width:"100%",
        paddingHorizontal:"5%",
        marginTop:margins.high,
        borderTopWidth:1,
        borderColor:colors.border_container
    },
    item_container:{
        width:"100%",
        padding:paddings.mid,
        marginTop:margins.high,
        borderWidth:1,
        borderColor:colors.border_container,
        borderRadius:4,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
    },
    item:{
        flexDirection:"row",
        alignItems:"center",
        columnGap:gaps.mid
    },
    radio_button:{
        width:20,
        height:20,
        borderWidth:1,
        borderColor:colors.border_container,
        borderRadius:10,
        justifyContent:"center",
        alignItems:"center",
    },
    dot:{
        width:12,
        height:12,
        borderRadius:6,
        backgroundColor:"#333333"
    },
    empty_text:{
        fontSize:fontsize.mid,
        fontWeight:fontweight.high,
        color:colors.light_black_text,
        textAlign:"center",
        marginTop:margins.high,
    },
    button_container:{
        width:"100%",
        padding:paddings.mid,
        paddingHorizontal:"5%",
        backgroundColor:colors.dark_white_container,
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        position:"absolute",
        bottom:0,
        zIndex:99999999
    },
    button:{
        width:"45%",
        padding:paddings.low,
        borderRadius:8,
        backgroundColor:"#2E2E2E",
    },
    button_text:{
        fontSize:fontsize.mid,
        fontWeight:fontweight.high,
        color:colors.white_text,
        textAlign:"center",
    },
    border_button:{
        width:"45%",
        padding:paddings.low,
        borderRadius:8,
        borderWidth:1,
        borderColor:"#2E2E2E",
        backgroundColor:colors.white_container
    },
    border_button_text:{
        fontSize:fontsize.mid,
        fontWeight:fontweight.high,
        color:"#2E2E2E",
        textAlign:"center",
    }
});

export default mobileStyle;