export default colors = {
    theme_container:"#030508",
    theme_text:"#030508",
    light_theme_container:"#2A2929", // "#16171B",      
    light_theme_text:"#2A2929",      // "#16171B", 
    dark_theme_container:"#010203",
    dark_theme_text:"#010203",  
    second_theme_container:"#6A73ED",
    second_theme_text:"#6A73ED",
    third_theme_container:"#BA424B",
    third_theme_text:"#BA424B",
    border_container:"#E1E1E1",
    border_text:"#E1E1E1",
    white_container:"white",
    white_text:"white",
    black_container:"black",
    black_text:"black",
    gray_container:"#9B9B9C",
    gray_text:"#9B9B9C",
    dark_white_container:"#FAFAFA",
    dark_white_text:"#FAFAFA",
    light_black_container:"#666666",
    light_black_text:"#666666",
    text_container:"#FAFCFB",
    text_text:"#FAFCFB",
};